---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "hyphy_removedups"
description: "Removes duplicate sequences from a FASTA file using HyPhy's built-in functionality"
keywords:
  - hyphy
  - deduplication
  - sequences
  - fasta
  - phylogenetics
tools:
  - "hyphy":
      description: "An open-source software package for comparative sequence analysis using stochastic evolutionary models."
      homepage: "https://hyphy.org"
      documentation: "https://hyphy.org"
      tool_dev_url: "https://github.com/veg/hyphy"
      doi: ""
      licence: ["MIT"]
      identifier: biotools:HyPhy

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1' ]`
  - fasta:
      type: file
      description: Input FASTA file containing sequences that may have duplicates
      pattern: "*.fasta"
      ontologies:
        - edam: "http://edamontology.org/format_1929"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1' ]`
  - deduplicated:
      type: file
      description: FASTA file with duplicate sequences removed
      pattern: "*.fasta"
      ontologies:
        - edam: "http://edamontology.org/format_1929"
  - versions:
      - "versions.yml":
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@hverdonk"
maintainers:
  - "@hverdonk"
  - "@dcallan"
