---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "hyphy_busted"
description: Test for episodic diversifying selection using HyPhy BUSTED.
keywords:
  - hyphy
  - selection
  - phylogenetics
  - genomics
  - diversifying selection
tools:
  - "hyphy":
      description: "An open-source software package for comparative sequence analysis using stochastic evolutionary models."
      homepage: "https://veg.github.io/hyphy-site/"
      documentation: "https://github.com/veg/hyphy/wiki"
      tool_dev_url: "https://github.com/veg/hyphy"
      doi: "10.1093/molbev/msu400"
      licence: ["MIT"]
      identifier: biotools:HyPhy

input:
  - alignment:
      type: file
      description: Multiple sequence alignment file in FASTA format.
      pattern: "*.fasta$"
      ontologies:
        - edam: "http://edamontology.org/format_1929"
  - tree:
      type: file
      description: Phylogenetic tree file in Newick format.
      pattern: "*.treefile"
      ontologies:
        - edam: "http://edamontology.org/format_1910"

output:
  - busted_json:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information (e.g. `[ id:'sample1' ]`)
      - "{id}.BUSTED.json":
          type: file
          description: JSON file containing episodic diversifying selection test results.
          pattern: "BUSTED/*.BUSTED.json"
          ontologies:
            - edam: "http://edamontology.org/format_3464"
  - versions:
      - "versions.yml":
          type: file
          description: File containing software version information
          pattern: "versions.yml"

authors:
  - "@hverdonk"
maintainers:
  - "@hverdonk"
  - "@d-callan"
