repository_type: pipeline

nf_core_version: 3.2.1

lint:
  actions_awsfulltest: false
  multiqc_config: false
  pipeline_name_conventions: false
  nf_test_content:
    - tests/default.nf.test
    - tests/main.nf.test
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - params.input
  files_exist:
    - CODE_OF_CONDUCT.md
    - .github/workflows/nf-test.yml
    - .github/actions/get-shards/action.yml
    - .github/actions/nf-test/action.yml
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - LICENSE.md
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - .github/workflows/linting.yml
    - .github/workflows/linting_comment.yml
    - assets/email_template.html
    - assets/email_template.txt
    - assets/sendmail_template.txt
    - docs/README.md

template:
  org: nf-core
  name: CAPHEINE
  description: Automated evolutionary annotation of existing datasets using Nextflow
  author: Hannah Verdonk, Danielle Callan
  version: '1.1'
  force: true
  outdir: .
  is_nfcore: true
