---
name: "HYPHYMPI_PRIME"
description: Analyze property-informed models of evolution using the MPI implementation of HyPhy PRIME.
keywords:
  - hyphy
  - mpi
  - selection
  - phylogenetics
  - genomics
  - amino acid properties
tools:
  - "hyphy":
      description: "An open-source software package for comparative sequence analysis using stochastic evolutionary models."
      homepage: "https://veg.github.io/hyphy-site/"
      documentation: "https://github.com/veg/hyphy/wiki"
      tool_dev_url: "https://github.com/veg/hyphy"
      doi: "10.1093/molbev/msu400"
      licence: ["MIT"]
      identifier: biotools:HyPhy
input:
  - alignment:
      type: file
      description: Multiple sequence alignment file in FASTA format.
      pattern: "*.fasta$"
  - tree:
      type: file
      description: Phylogenetic tree file in Newick format.
      pattern: "*.treefile"
output:
  - prime_json:
      type: file
      description: JSON file containing property-informed evolution analysis results.
      pattern: "PRIME/*.PRIME.json"
  - versions:
      - "versions.yml":
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@hverdonk"
maintainers:
  - "@hverdonk"
  - "@d-callan"
