---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "seqkit_split"
description: "Split FASTA/Q files into multiple files based on sequence IDs"
keywords:
  - split
  - fasta
  - fastq
  - sequences
  - genomics
tools:
  - "seqkit":
      description: "a cross-platform and ultrafast toolkit for FASTA/Q file manipulation"
      homepage: "https://bioinf.shenwei.me/seqkit/"
      documentation: "https://bioinf.shenwei.me/seqkit/usage/#split"
      tool_dev_url: "https://github.com/shenwei356/seqkit"
      doi: "10.1371/journal.pone.0163962"
      licence: ["MIT"]
      identifier: biotools:seqkit

input:
  - ref_fasta:
      type: file
      description: Input FASTA/Q file to be split
      pattern: "*.{fasta,fa,fastq,fq}"
      ontologies:
        - edam: "http://edamontology.org/format_1929"
        - edam: "http://edamontology.org/format_1930"

output:
  - "*.fasta":
      type: file
      description: Split FASTA files, one per sequence
      pattern: "*.fasta"
      ontologies:
        - edam: "http://edamontology.org/format_1929"
  - versions:
      - "versions.yml":
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@hverdonk"
maintainers:
  - "@hverdonk"
