---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "hyphy_relax"
description: Run HyPhy RELAX for detecting relaxed selection.
keywords:
  - hyphy
  - selection
  - phylogenetics
  - genomics
tools:
  - "hyphy":
      description: "An open-source software package for comparative sequence analysis using stochastic evolutionary models."
      homepage: "https://veg.github.io/hyphy-site/"
      documentation: "https://github.com/veg/hyphy/wiki"
      tool_dev_url: "https://github.com/veg/hyphy"
      doi: "10.1093/molbev/msu400"
      licence: ['Custom']
      identifier: biotools:HyPhy

input:
  - alignment:
      type: file
      description: Multiple sequence alignment file in FASTA format.
      pattern: "*.fasta$"
      ontologies:
        - edam: "http://edamontology.org/format_1929"
  - tree:
      type: file
      description: Phylogenetic tree file in Newick format.
      pattern: "*.treefile"
      ontologies:
        - edam: "http://edamontology.org/format_1910"
          
output:
  - relax_json:
      type: file
      description: JSON file containing relaxed selection analysis results.
      pattern: "*.RELAX.json"
      ontologies:
        - edam: "http://edamontology.org/format_3464"
          
  - versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@hverdonk"
maintainers:
  - "@hverdonk"
  - "@d-callan"

