# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "process_viral_nonrecombinant"
description: Process viral non-recombinant sequences for phylogenetic analysis
keywords:
  - phylogenetics
  - genomics
  - viral sequences
  - sequence processing
  - molecular evolution

components:
  - removeambigseqs
  - cawlign
  - removedups
  - iqtree
  - labeltree
input:
  - ch_unaligned:
      type: file
      description: |
        Channel containing unaligned viral sequences
        Structure: [ val(meta), path(unaligned_sequences) ]
      pattern: "*.fasta"
  - ch_reference:
      type: file
      description: |
        Channel containing reference gene for sequence alignment
        Structure: [ val(meta), path(reference_gene) ]
      pattern: "*.fasta"
  - ch_foreground:
      type: list
      description: |
        List of foreground sequences for tree labeling
        Structure: [ foreground_sequences_list ]
output:
  - cleaned_seqs:
      type: file
      description: |
        Channel containing sequences with a low percentage of gaps and ambiguous bases
        Structure: [ val(meta), path(cleaned_sequences) ]
      pattern: "*-clean.fasta"
  - aligned_seqs:
      type: file
      description: |
        Channel containing aligned viral sequences
        Structure: [ val(meta), path(aligned_sequences) ]
      pattern: "*.aligned.fasta"
  - deduplicated_seqs:
      type: file
      description: |
        Channel containing deduplicated viral sequences
        Structure: [ val(meta), path(deduplicated_sequences) ]
      pattern: "*.deduplicated.fasta"
  - phylogeny:
      type: file
      description: |
        Phylogenetic tree generated by IQTree
        Structure: [ path(tree_file) ]
      pattern: "*.treefile"
  - labeled_tree:
      type: file
      description: |
        Phylogenetic tree with foreground sequences labeled
        Structure: [ path(tree_file) ]
      pattern: "*.treefile"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@hverdonk"
maintainers:
  - "@hverdonk"
