# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "process_viral_nonrecombinant"
description: Process viral non-recombinant sequences for phylogenetic analysis
keywords:
  - phylogenetics
  - genomics
  - viral sequences
  - sequence processing
  - molecular evolution
components:
  - removeambigseqs
  - removeterminalstopcodon
  - seqkit/split
  - cawlign
  - hyphy/cln
  - iqtree
  - hyphy/labeltree/list
  - hyphy/labeltree/regexp
input:
  - ch_unaligned:
      type: file
      description: |
        Channel containing unaligned viral sequences
        Structure: [ val(meta), path(unaligned_sequences) ]
      pattern: "*.fasta"
  - ch_reference:
      type: file
      description: |
        Channel containing reference gene for sequence alignment
        Structure: [ val(meta), path(reference_gene) ]
      pattern: "*.fasta"
  - ch_foreground_list:
      type: list
      description: |
        List of foreground sequences for tree labeling
        Structure: [ foreground_sequences_list ]
  - ch_foreground_regexp:
      type: string
      description: |
        Regular expression to match foreground sequences for tree labeling
        Structure: [ val(regexp) ]
output:
  - deduplicated:
      type: file
      description: |
        Channel containing viral sequences that have been cleaned, deduplicated, and aligned.
        Structure: [ val(meta), path(deduplicated_sequences) ]
      pattern: "*.deduplicated.fasta"
  - tree:
      type: file
      description: |
        Phylogenetic tree generated by IQTree, possibly labeled with foreground sequences by HYPHY labeltree
        Structure: [ path(tree_file) ]
      pattern: "*.treefile"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@hverdonk"
maintainers:
  - "@hverdonk"
  - "@d-callan"
