---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "hyphy_cln"
description: "Convert sequence names to HyPhy valid identifiers if needed and replace stop codons with gaps in codon data if any are present."
keywords:
  - clean
  - genomics
  - hyphy
  - alignment
tools:
  - "hyphy":
      description: "An open-source software package for comparative sequence analysis using stochastic evolutionary models."
      homepage: "https://hyphy.org"
      documentation: "https://hyphy.org"
      tool_dev_url: "https://github.com/veg/hyphy"
      doi: ""
      licence: ["MIT"]
      identifier: biotools:HyPhy

input:
  - meta:
      type: map
      description: Groovy Map containing sample information, e.g. `[ id:'sample1' ]`
  - alignment:
      type: file
      description: Multiple sequence alignment file.
      pattern: "*.*"
      ontologies:
        - edam: "http://edamontology.org/format_1929"

output:
  - deduplicated_seqs:
      - meta:
          type: map
          description: Groovy Map containing sample information, e.g. `[ id:'sample1' ]`
      - "{id}-nodups.*":
          type: file
          description: Output alignment with HyPhy-valid identifiers and stop codons handled.
          pattern: "CLN/*-nodups.*"

  - versions:
      - "versions.yml":
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@hverdonk"
maintainers:
  - "@hverdonk"
