---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "removeambigseqs"
description: Remove sequences with excessive ambiguous bases from a FASTA file
keywords:
  - fasta
  - sequence filtering
  - genomics
  - bioinformatics
tools:
  - "filter-ambig-sequences.py":
      description: "Custom Python script to filter out sequences with excessive ambiguous bases"
      homepage: ""
      documentation: ""
      tool_dev_url: ""
      doi: ""
      licence: ""
      identifier: ""

input:
  # Only when we have meta
  - - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`

  - input_seqs:
      type: file
      description: Input FASTA file to filter for sequences with low ambiguous base content
      pattern: "*.fasta"
      ontologies:
        - edam: "http://edamontology.org/format_1929"

output:
  - cleaned_seqs:
      type: file
      description: FASTA file with sequences filtered to remove those with excessive ambiguous bases
      pattern: "*-clean.fasta"

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
      ontologies:
        - edam: "http://edamontology.org/format_1929"

authors:
  - "@hverdonk"
maintainers:
  - "@hverdonk"
  - "@d-callan"
